### PR TITLE
Added translations for ca, en_GB, es, fur, tr

### PR DESCRIPTION
**Pull request by humdingerb**
Imported from Polyglot. Thanks to:

Catalan (ca)	Davidmp
Friulian (fur)	tmtfx
Spanish (es)	cafeina
Turkish (tr)	Emir Sarı

### CODE REVIEW

**Comment by humdingerb** [comment]
If you wanted to make an "official" release of it, maybe increase the version in PDFTranslator.rdef first.

**Comment by threedeyes** [comment]
Yes, sure

**Comment by humdingerb** [comment]
Thanks. I'll update the haikuports recipe.

**Comment by threedeyes** [comment]
https://github.com/threedeyes/PDFTranslator/releases

**Pull request merged**
